### ISSUE TITLE
Add categories to initial search page

### ISSUE THREAD

**Issue by clarkbw** [mozilla/fifi#13]
Anthony has a design for categories we need to implement.  Even if we have to hard code the backend initially it will be good to get this going.

**Comment by antlam** [comment]
For quick visual reference.

![screen shot 2013-10-10 at 10 26 42 am](https://f.cloud.github.com/assets/1994820/1308605/580df9ae-31d1-11e3-9c77-7b586de7be86.png)

We can ignore "Quick search" for the time being and just focus on "News". Currently working on the "News" page as per our last meeting discussions.
