### ISSUE TITLE
3 suggestions from each engine

### ISSUE THREAD

**Issue by clarkbw** [mozilla/fifi#2]
Here's a screenshot of what we're aiming for:
![screen shot 2013-08-13 at 10 02 18](https://f.cloud.github.com/assets/2134/957690/2d2fe984-0456-11e3-841b-8a8718313718.png)

Only unique terms show and there's no hint of where they come from even though they may have come from different engines.

Right now we'll control the order of the engines like the following.
Google, Yelp, Amazon, Wikipedia |Yelp, Amazon, Wikipedia.

First using the term typed into the input:
Google (3 suggestions), Yelp (3 suggestions), Amazon (3 suggestions), Wikipedia (3 suggestions)

The second set uses the first returned suggestion from Google, so if Google returned "kittens for sale" as the first suggestions for the term "kittens" we send "kittens for sale" to all these engines.
Yelp (3 suggestions), Amazon (3 suggestions), Wikipedia (3 suggestions)

We don't have to ensure that each engine uses it's 3 spaces since non-unique terms will be tossed and engines could have returned duplicates of other engines.  Later we can tweak settings for returning more search terms to get a larger average list of unique terms.

**Comment by operatorjen** [comment]
https://github.com/mozilla/fifi/commit/662609c9d703d298e925f09586e6582f492ab918

yelp doesn't seem to be pulling in anything so i have to investigate their api or see what's up. but that should fix it for now.
