### ISSUE TITLE
search suggestions don't always match the terms in the input

### ISSUE THREAD

**Issue by clarkbw** [mozilla/fifi#3]
through a little fast typing you can get into a state where the terms in the input are obviously different than the suggestion results being shown.  We probably need to double check the filter of results being returned.

**Comment by operatorjen** [comment]
probably the keydown thing you mentioned?

**Comment by operatorjen** [comment]
https://github.com/mozilla/fifi/commit/2081ad6a3d96b2aeefeb77cd882d869ee91f3c87
