### ISSUE TITLE
suggestions from the first web search engine suggestion

### ISSUE THREAD

**Issue by clarkbw** [mozilla/fifi#4]
The server is providing additional suggestions we need to display.  The first suggestion returned from google is being using against the alternate engines and returned, these suggestions should be listed after the initial set we have.

**Comment by clarkbw** [comment]
this shizzle needs a vizzle
http://cl.ly/image/2Z0v3c1g182H

**Comment by operatorjen** [comment]
So I'm looking at this right now and I think we originally had decided to group concepts together? Which means this viz doesn't really work with our current structure? (We made the concepts grouped to avoid duplication - but I'm not following how this works with the current setup). I guess we can confirm at the meeting?

**Comment by clarkbw** [comment]
This should, at least the idea is to, give us more unique concepts.

Here's the pseudo code:

```
term = sushi
google(term) returns [ 'sushi cat', 'sushi samba', 'sushi rice' ]
amazon(term) returns [ 'sushi making kit', 'sushi knife', 'sushi kit' ]
yelp(term) returns [ 'sushi buffet', 'sushi delivery', 'sushi all you can eat' ]
// google[0] == 'sushi cat'
amazon(google[0]) returns [ 'sushi cat plush', 'sushi cat plushie', 'sushi cat plush toy' ]
yelp(google[0]) returns [ 'sushi caterer' ]
```

concepts are still grouped when strings are equal but by taking the `google[0]` as a second run we get faster results.  This is especially true when people haven't finished the term; when `sushi` has only been typed as `sus` google returns `sushi` as `google[0]` and as such the other engines get a second chance to answer better.

**Comment by clarkbw** [comment]
```
google(term)[0]  google(term)[1] google(term)[2]
wikipedia(term)[0]  wikipedia(term)[1] wikipedia(term)[2]
amazon(term)[0]  amazon(term)[1] amazon(term)[2]
yelp(term)[0]  yelp(term)[1] yelp(term)[2]
amazon(google(term)[0])[0] amazon(google(term)[0])[1] amazon(google(term)[0])[2]
yelp(google(term)[0])[0] yelp(google(term)[0])[1] yelp(google(term)[0])[2]
wikipedia(google(term)[0])[0] wikipedia(google(term)[0])[1] wikipedia(google(term)[0])[2]
```

which is a list of 21 boxes containing a string each; we remove duplicates, so that each engine always returns, at maximum, 3 unique phrases, even if their top results have matched other engines; we don't have branding.  These boxes are sorted as above.

**Comment by operatorjen** [comment]
I believe this is complete. Closing.
