### ISSUE TITLE
results page updates on blur event

### ISSUE THREAD

**Issue by davidascher** [mozilla/fifi#8]

**Comment by operatorjen** [comment]
@davidascher can you give me a step by step of what error you are getting? When I have a blur event on the input field it appears to work as expected.

**Comment by davidascher** [comment]
STRs:
- type in sushi
- get results that are about sush
- alt-tab so that the browser loses focus
  -> results update to show sushi results
- alt-tab to give the browser focus
  -> results refresh.

**Comment by clarkbw** [comment]
It's the keydown stroke in the alt-tab that causes the refresh for the
right results.  Not actually tied to the blur event.

**Comment by operatorjen** [comment]
https://github.com/mozilla/fifi/commit/bb9cac3ca2feadd9eeae48fefad7088fb8fbaefb
